### ISSUE TITLE
rofi-wifi-menu seems to be trying use the security type as SSID

### ISSUE THREAD

**Issue by Bertieio** [zbaylin/rofi-wifi-menu#3]
I'm trying to setup rofi-wifi-menu on Arch with openbox but keep getting the error below it seems to be trying to use the security type as the SSID

![image](https://user-images.githubusercontent.com/9221294/27884988-3b44d6ea-61ce-11e7-9cad-726d70dddb22.png)

**Comment by mateossh** [comment]
I have the same error. Also on Arch

**Comment by mateossh** [comment]
I found out what's wrong. CHSSID variable (line 56) gets second "part" of string from selected entry in Rofi. In default config fields are in order: "SSID, security, bars".  So CHSSID has wrong value which is security type.

@Bertieio quick fix: either change FIELDS value in config to (for example) "BARS,SSID,SECURITY" or change line 56 from:
`CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $2}')`
to
`CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $1}')`

**Comment by zbaylin** [comment]
Yes you're correct. I fixed it in my local repository but for some reason forgot to commit it. I will fix it soon.

--
Zachary Baylin

**Comment by zbaylin** [comment]
Okay I temporarily fixed it but I'm going to keep the issue open because it only works because I hardcoded the position of the SSID field. I will fix it so it will always work.
